export const products = [
  "Ultimate Perfume Box",
  "Perfume Gift Set For Men",
  "Perfume Gift Set For Women",
  "Under Eye Cream for Dark Circles",
  "Perfume For Men",
  "Perfume For Women",
  "Unisex Perfume",
];
export const websitePages = [
  "Blogs",
  "Newsroom",
  "Terms & Conditions",
  "Privacy Policy",
  "Refund and Return",
  "Shipping Policy",
  "Bulk Order - GST Invoice",
];
export const footerLinks = [
  "About Us",
  "Contact Us",
  "Order Tracking",
  "All Products",
  "FAQ",
  "Sitemap",
];
export const officeDetails = [
  "Office Location: Plot no. 417, Udyog Vihar Phase III, Gurgaon, Haryana, India",
  "Contact Us on WhatsApp",
  "+91-9311732440",
  "10:00 AM to 7:00 PM, Monday to Sunday",
];
export const productCategories = [
  "Perfume",
  "Best perfume for men",
  "Attar",
  "Ittar",
  "Attar perfume",
  "Oud attar",
  "Best attar for women",
  "Best attar for men",
  "Perfume for men",
  "Vitamin C Face Wash",
  "Perfume for women",
  "Best perfume for women",
  "Perfume set for women",
  "Gift for Men",
  "Face wash for oily skin",
  "Body scrub",
  "Dark circle",
  "Perfume for girls",
  "Dark circles removal cream",
  "Acne face wash",
  "Under eye cream",
  "Gift sets for women",
  "Body wash for women",
  "Pocket perfume for men",
  "De tan face pack",
  "Pimple removal cream",
  "Lip scrub",
  "Tan removal face pack",
  "Face wash for acne",
  "Exfoliate scrub",
  "Gift set for men",
  "Coffee Body Scrub",
  "Best long lasting perfume for men",
  "Perfumes for men under 500",
  "Perfumes for women under 500",
  "Perfume gift sets",
  "Oud perfume",
  "Ceo perfume",
  "Under eye cream for dark circles",
  "Acne cream",
  "Vitamin C cream for face",
  "Body lotion for women",
  "Long lasting perfume for women",
  "Perfume gift pack for her",
  "Perfume gift pack for him",
  "Charcoal face wash",
  "Body wash for men",
  "Best shower gel for women",
  "Shower Gel for men and Women",
  "Body lotion for dry skin",
  "Body Lotion for men",
  "Body Lotion for women",
  "Shower Gel and Perfume Combo",
  "Shower Travel Kit",
  "Travel Mini Kit",
  "Birthday Gift for Women/Girls",
  "Wedding Gifts for Couples",
  "Gifts for Men Under 500",
  "Gifts for Women Under 500",
  "Diwali Gift Ideas",
  "Gifts for Men Under 500",
  "Gifts for Women Under 500",
  "Corporate Gifts",
];
export default async function getData({setData}){
  const data = await fetch('');
  const demoData = data.json();
  setData(demoData);
}
  
